Module.preRun = () => {
    const PREFIX = "/share/ucblogo";
    ENV.LOGOLIB = PREFIX + "/logolib";
    ENV.LOGOHELP = PREFIX + "/helpfiles";
    ENV.CSLS = PREFIX + "/csls";
};
Module.env = {};
Module.graphics = {};
Module.graphics.prepare_to_draw = () => { console.log("prepare_to_draw") };
Module.graphics.done_drawing = () => { console.log("done_drawing") };
Module.graphics.prepare_to_exit = (v) => { console.log(`prepare_to_exit(${v})`) };
Module.graphics.clear_screen = () => { console.log("clear_screen") };
Module.graphics.prepare_to_draw = () => { console.log(`prepare_to_draw ${[]}`) };
Module.graphics.done_drawing = () => { console.log(`done_drawing ${[]}`) };
Module.graphics.prepare_to_exit = (v) => { console.log(`prepare_to_exit ${[v]}`) };
Module.graphics.clear_screen = () => { console.log(`clear_screen ${[]}`) };
Module.graphics.line_to = (x, y) => { console.log(`line_to ${[x, y]}`) };
Module.graphics.move_to = (x, y) => { console.log(`move_to ${[x, y]}`) };
Module.graphics.draw_str = (s) => { console.log(`draw_str ${[s]}`) };
Module.graphics.set_pen_vis = (v) => { console.log(`set_pen_vis ${[v]}`) };
Module.graphics.set_pen_mode = (m) => { console.log(`set_pen_mode ${[m]}`) };
Module.graphics.set_pen_color = (c) => { console.log(`set_pen_color ${[c]}`) };
Module.graphics.set_pen_width = (w) => { console.log(`set_pen_width ${[w]}`) };
Module.graphics.set_pen_height = (h) => { console.log(`set_pen_height ${[h]}`) };
Module.graphics.set_pen_x = () => { console.log(`set_pen_x ${[]}`) };
Module.graphics.set_pen_y = () => { console.log(`set_pen_y ${[]}`) };
Module.graphics.set_back_ground = (c) => { console.log(`set_back_ground ${[c]}`) };
Module.graphics.pen_reverse = () => { console.log(`pen_reverse ${[]}`) };
Module.graphics.pen_erase = () => { console.log(`pen_erase ${[]}`) };
Module.graphics.pen_down = () => { console.log(`pen_down ${[]}`) };
Module.graphics.full_screen = () => { console.log(`full_screen ${[]}`) };
Module.graphics.split_screen = () => { console.log(`split_screen ${[]}`) };
Module.graphics.text_screen = () => { console.log(`text_screen ${[]}`) };
Module.graphics.save_pen = (p) => { console.log(`save_pen ${[p]}`) };
Module.graphics.restore_pen = (p) => { console.log(`restore_pen ${[p]}`) };
Module.graphics.plain_xor_pen = () => { console.log(`plain_xor_pen ${[]}`) };
Module.graphics.label = (s) => { console.log(`label ${[s]}`) };
Module.graphics.tone = (pitch, duration) => { console.log(`tone ${[pitch, duration]}`) };
Module.graphics.set_pen_pattern = (pat) => { console.log(`set_pen_pattern ${[pat]}`) };
Module.graphics.get_pen_pattern = (pat) => { console.log(`get_pen_pattern ${[pat]}`) };
Module.graphics.set_list_pen_pattern = (pat) => { console.log(`set_list_pen_pattern ${[pat]}`) };
Module.graphics.prepare_to_draw_turtle = () => { console.log(`prepare_to_draw_turtle ${[]}`) };
Module.graphics.web_done_drawing_turtle = () => { console.log(`web_done_drawing_turtle ${[]}`) };
Module.graphics.logofill = () => { console.log(`logofill ${[]}`) };
Module.graphics.set_palette = (i, c1, c2, c3) => { console.log(`set_palette ${[i, c1, c2, c3]}`) };
Module.graphics.get_pallette = () => { console.log(`get_pallette ${[]}`) };
Module.graphics.erase_screen = () => { console.log(`erase_screen ${[]}`) };